namespace ErikaBladh.DessertAnimalsDataBase.DataAccess;

using System.Data.SQLite;

public class SQLiteDataAccess : IDataAccess
{
	private readonly SQLiteConnection _connection;

	public SQLiteDataAccess(string dbPath)
	{
		bool dbExists = File.Exists(dbPath);
		_connection = new SQLiteConnection($"Data Source={dbPath}");
		_connection.Open();
		if (!dbExists) PopulateDatabase();
	}


	public int DoNonQuery(string sql, Dictionary<string, string>? parameters = null)
	{
		var command = new SQLiteCommand(sql, _connection);
		if (parameters is not null) AddParametersToCommand(command, parameters);
		return command.ExecuteNonQuery();
	}

	public string[][] DoQuery(string sql, Dictionary<string, string>? parameters = null)
	{
		var command = new SQLiteCommand(sql, _connection);
		if (parameters is not null) AddParametersToCommand(command, parameters);
		var result = new List<string[]>();
		var reader = command.ExecuteReader();
		while (reader.Read())
		{
			var row = new List<string>();
			for (var i = 0; i < reader.FieldCount; i++)
			{
				row.Add(reader.GetValue(i).ToString() ?? "");
			}
			result.Add(row.ToArray());
		}
		return result.ToArray();
	}

	private void AddParametersToCommand(SQLiteCommand command, Dictionary<string, string> parameters)
	{
		foreach (var p in parameters)
		{
			command.Parameters.AddWithValue(p.Key, p.Value);
		}
	}
	private void PopulateDatabase()
	{
		DoNonQuery(@"
		CREATE TABLE IF NOT EXISTS 'Animals' (
			Id INTEGER PRIMARY KEY AUTOINCREMENT,
			Name TEXT NOT NULL,
			Description TEXT NOT NULL
		);");
		// Animals and their descriptions were generated by ChatGPT at chat.openai.com
		DoNonQuery(@"
		INSERT INTO Animals (Name, Description) VALUES
			    ('Cocoaconda', 'Slithering through the chocolate jungles, the Cocoaconda is a mesmerizing creature with scales that mimic the rich hues of cocoa. Known for its sweet venom, it navigates the world with a sinuous grace, blending into its surroundings while guarding the secrets of the confectionery realm.'),
			    ('Macaroonkey', 'High up in the treetops of the pastry canopy, the Macaroonkey swings from branch to branch. Its colorful fur mimics the vibrant hues of macarons, and it is known for its mischievous antics. This playful creature often gathers sweet treats, creating a stash of macarons hidden away in the treetops.'),
			    ('Lollipopard', 'Graceful and adorned with swirling patterns, the Lollipopard prowls through the Candy Savannah. Its fur resembles the vibrant colors of lollipops, and its long, lollipop-patterned tail is both a stunning display and a mesmerizing tool for catching the attention of prey.'),
			    ('Souffléphant', 'Majestic and airy, the Souffléphant roams the Dessert Plains with a gentle presence. Its frothy fur mimics the delicate rise of a soufflé, and its trumpeting calls echo through the baking winds. Known for its wisdom, it serves as a guardian of the sweet landscapes.'),
			    ('Strawberrynoceros', 'Charging through the Berry Meadows, the Strawberrynoceros is a formidable sight. With a horn resembling a giant strawberry, this creature grazes on the sweet grasses, contributing to the ecosystem with its berry-rich droppings. Its presence adds a touch of fruity allure to the vast dessert landscape.');
		");
	}
}
